databases:
  - name: traveary_db
    databaseName: traveary_db
    user: Traveary
    region: singapore

services:
  - type: web
    name: Traveary
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: traveary_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false