default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: Traveary_development
  host: db

test:
  <<: *default
  database: Traveary_test

production:
  <<: *default
  database: Traveary_production
  username: Traveary
  password: <%= ENV["TRAVEARY_DATABASE_PASSWORD"] %>