default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: traveary_development

test:
  <<: *default
  database: traveary_test


production:
  <<: *default
  database: traveary_production
  #username: <%= ENV["TRAVEARY_DATABASE_USERNAME"] %>
  #password: <%= ENV["TRAVEARY_DATABASE_PASSWORD"] %>
